server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thitructuyen?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh
# Thư mục lưu trữ file ảnh
app:
  upload-dir: uploads/
